# Generated by Django 4.1.7 on 2023-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('mobileNumber', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('aadharNumber', models.CharField(max_length=15, verbose_name='Aadhar Number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
    ]
