# Generated by Django 4.1.7 on 2023-09-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Doctor Name')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('mobileNumber', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('aadharNumber', models.CharField(max_length=15, verbose_name='Aadhar Number')),
                ('role', models.CharField(max_length=15, verbose_name='Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default=1, max_length=15, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
