# Generated by Django 4.1.7 on 2023-09-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_receptionist_remove_doctor_city_doctor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
    ]
