# Generated by Django 4.1.7 on 2023-09-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_receptionist_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receptionist',
            new_name='Staff',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
