# Generated by Django 4.1.7 on 2023-09-19 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_rename_receptionist_staff_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(default='Male', max_length=50, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 9, 20)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
    ]
