# Generated by Django 4.1.7 on 2023-09-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_patient_gender_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Gender',
            new_name='gender',
        ),
    ]
