# Generated by Django 4.0.1 on 2023-09-23 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_patient_diagnosis_patient_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2023, 9, 23)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default='None', max_length=100, verbose_name='Symptoms'),
        ),
    ]
