# Generated by Django 4.2.5 on 2024-04-04 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_alter_patient_dateofbirth_alter_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
    ]
